-- Объединение таблиц LIGHT_DOT и SHARP
CREATE TABLE LIGHT_DOT_DENORM AS
SELECT LD.*, S.COUNT 
FROM LIGHT_DOT LD JOIN SHARP S ON LD.SHARP_ID = S.SHARP_ID;

-- Добавление количества панелей в таблицу BUILDING
ALTER TABLE BUILDING ADD COLUMN PANEL_COUNT INT DEFAULT 0;
