PERSON:
PERSON_ID → (NAME, HEIGHT, AGE, GENDER)

BUILDING:
BUILDING_ID → (NAME, HEIGHT, MATERIAL)

PANEL:
PANEL_ID → (TYPE, OPACITY, TEMPERATURE, BUILDING_ID)

SHARP:
SHARP_ID → (COUNT)

LIGHT_DOT:
LIGHT_DOT_ID → (BRIGHTNESS, COLOR, POS_X, POS_Y, POS_Z, BUILDING_ID, SHARP_ID)

VIEW:
(PERSON_ID, BUILDING_ID) → ()
